# Generated by Django 4.2.21 on 2025-05-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_waterbill_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscriber')),
                ('water_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.waterbill')),
            ],
        ),
    ]
