# Generated by Django 4.2.21 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriberledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='billing_month',
            field=models.DateField(),
        ),
    ]
