# Generated by Django 4.2.21 on 2025-06-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_waterbill_billing_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberledger',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriberledger',
            name='water_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.waterbill'),
        ),
    ]
